---
title: "Homework_week_4"
author: "May Dixon"
date: "September 28, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Prompt  

Every Saturday, at the same time, a primatologist goes and sits in the forest in the morning and listens for titi monkey calls, counting the number of calls they hear in a 2 hour window from 5am to 7am. Based on previous knowledge, she believes that the mean number calls she will hear in that time is exactly 15. Let X represent the appropriate Poisson random variable of the number of calls heard in each monitoring session.

What is the probability that she will hear more than 8 calls during any given session?
What is the probability that she will hear no calls in a session?
What is the probability that she will hear exactly 3 calls in a session?
Plot the relevant Poisson mass function over the values in range 0 ≤ x ≤ 30.
Simulate 104 results from this distribution (i.e., 2 years of Saturday monitoring sessions).
Plot the simulated results using hist() and use xlim() to set the horizontal limits to be from 0 to 30. How does your histogram compare to the shape of the probability mass function you plotted above?
